#!/usr/bin/env bash
# DB-R0-4 — reproducible schema inventory (study-only). No database server required.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
FINDINGS_ROOT="$(cd "${WP_DIR}/../../../.." && pwd)"
LANGVERSE_ROOT="${LI_LANGVERSE_ROOT:-$(cd "${FINDINGS_ROOT}/.." && pwd)}"

AGENTS="${LANGVERSE_ROOT}/li-cursor-agents"
SUPA_DIR="${AGENTS}/supabase/migrations"
CATALOG="${AGENTS}/src/db/schema-catalog.ts"
LIDB_CP="${LANGVERSE_ROOT}/lidb/migrations/archive/002_control_plane_embedded.sql"
OUT="${WP_DIR}/snippets/supabase-tables-inventory.txt"

mkdir -p "$(dirname "$OUT")"

{
  echo "# Generated by DB-R0-4 reproduce.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "## Supabase migrations (create table)"
  grep -rniE 'create table (if not exists )?public\.' "$SUPA_DIR" || true
  echo
  echo "## CONTROL_PLANE_TABLES (schema-catalog.ts)"
  grep -n 'name: "' "$CATALOG" || true
  echo
  echo "## lidb archive control-plane smoke"
  if [[ -f "$LIDB_CP" ]]; then
    grep -niE 'CREATE TABLE|ALTER TABLE' "$LIDB_CP" || true
  else
    echo "MISSING: $LIDB_CP"
  fi
} | tee "$OUT"

echo
echo "Wrote ${OUT}"
echo "Done. See README.md for gap interpretation."
